language: generic

os:
  - linux
  - osx

env:
  - MYUSEMC=true MYPYTHON_VERSION=2.7
  - MYUSEMC=true MYPYTHON_VERSION=3.7
  - MYUSEMC=true MYPYTHON_VERSION=3.8
  - MYUSEMC=true MYPYTHON_VERSION=3.9
  - MYUSEMC=true MYPYTHON_VERSION=3.10
  - MYUSEMC=false

git:
  depth: 999999

branches:
  except:
    - /^v[0-9]/

addons:
  apt:
    packages:
    - python-numpy
    - python-setuptools


before_install:
  - MYNAME=diffpy.utils
  - MYCOMMIT="$(git rev-parse HEAD)"
  - umask 022
  - git fetch origin --tags
  - MYPYTHON=python; MYPIP=pip
  - NOSYS=true; NOAPT=true; NOBREW=true; NOMC=true
  - if ${MYUSEMC}; then
        NOMC=false;
    elif [[ ${TRAVIS_OS_NAME} == linux ]]; then
        NOAPT=false; NOSYS=false;
        MYPIPFLAGS="--user";
    elif [[ ${TRAVIS_OS_NAME} == osx ]]; then
        NOBREW=false; NOSYS=false;
        MYPYTHON=python3;
        MYPIP=pip3;
        MYPIPFLAGS="--user";
    fi
  - MYMCREPO=https://repo.anaconda.com/miniconda
  - case ${TRAVIS_OS_NAME} in
    linux)
        MYMCBUNDLE=Miniconda3-latest-Linux-x86_64.sh ;;
    osx)
        MYMCBUNDLE=Miniconda3-latest-MacOSX-x86_64.sh ;;
    *)
        echo "Unsupported operating system." >&2;
        exit 2 ;;
    esac
  - MYRUNDIR=${PWD}/build/rundir

  - mkdir -p ~/pkgs
  - mkdir -p ${MYRUNDIR}
  - cp .coveragerc ${MYRUNDIR}/

  - $NOMC || pushd ~/pkgs
  - $NOMC || wget --timestamping ${MYMCREPO}/${MYMCBUNDLE}
  - $NOMC || test -x ~/mc/bin/conda || bash ${MYMCBUNDLE} -b -f -p ~/mc
  - $NOMC || popd
  - $NOMC || source ~/mc/bin/activate base
  - $NOMC || conda update --yes conda
  - $NOMC || conda install --yes conda-build conda-verify jinja2
  - $NOMC || conda create --name=testenv --yes python=${MYPYTHON_VERSION} coverage

  - $NOAPT || test "${TRAVIS_OS_NAME}" = "linux" || exit $?
  - $NOAPT || PATH="$(echo "$PATH" | sed 's,:/opt/pyenv/[^:]*,,g')"
  - $NOAPT || test "$(which python)" = "/usr/bin/python" || (
                  which python; exit 1)

  - $NOBREW || test "${TRAVIS_OS_NAME}" = "osx" || exit $?
  - $NOBREW || brew update
  - $NOBREW || brew upgrade python
  - $NOBREW || brew install gcc || brew link --overwrite gcc

  - $NOSYS || devutils/makesdist
  - $NOSYS || MYTARBUNDLE="$(ls -t "${PWD}"/dist/*.tar.gz | head -1)"


install:
  - $NOMC || conda build --python=${MYPYTHON_VERSION} conda-recipe
  - $NOMC || conda render --python=${MYPYTHON_VERSION} --output conda-recipe |
                sed 's,.*/,,; s/[.]tar[.]bz2$//; s/-/=/g' > /tmp/mypackage.txt
  - $NOMC || source activate testenv
  - $NOMC || conda install --yes --use-local --file=/tmp/mypackage.txt

  - $NOSYS || $MYPIP install $MYPIPFLAGS coverage
  - $NOSYS || $MYPIP install $MYPIPFLAGS "${MYTARBUNDLE}"

  - cd ${MYRUNDIR}
  - MYGIT_REV=$($MYPYTHON -c "import ${MYNAME}.version as v; print(v.__git_commit__)")
  - if [[ "${MYCOMMIT}" != "${MYGIT_REV}" ]]; then
        echo "Version mismatch ${MYCOMMIT} vs ${MYGIT_REV}.";
        exit 1;
    fi


before_script:
  - $NOBREW || USER_BASE="$($MYPYTHON -c 'import site; print(site.USER_BASE)')"
  - $NOBREW || PATH="${USER_BASE}/bin:${PATH}"


script:
  - coverage run --source ${MYNAME} -m ${MYNAME}.tests.run


after_success:
  - $MYPIP install $MYPIPFLAGS codecov
  - codecov
